{
 "title": "Gefjun",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "celsius" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Celsius",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "celsius" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lux",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "targets": [
    {
     "alias": "Sensor 1",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "lights",
     "select": [
      [
       { "params": [ "lux" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "sensor1" }
     ]
    },
    {
     "alias": "Sensor 2",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "lights",
     "select": [
      [
       { "params": [ "lux" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "sensor2" }
     ]
    }
   ]
  },
  {
   "title": "Lux",
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Sensor 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "lights",
     "select": [
      [
       { "params": [ "lux" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "sensor1" }
     ]
    },
    {
     "alias": "Sensor 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "lights",
     "select": [
      [
       { "params": [ "lux" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "sensor2" }
     ]
    }
   ]
  },
  {
   "title": "Light on?",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "light",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Light on?",
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "On",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "light",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}